### ISSUE TITLE
Add additional Topics

### ISSUE THREAD

**Issue by ericdrosado** [rawheel/MyUnfollowers-App#6]
In Community Exchange, GitHub Topics will help the discoverability of your project.

I see that you already have great topics on your repository! If you happened to use any offers in the [GitHub Student Developer Pack](https://education.github.com/pack#offers) to build this project, I would recommend adding the name of the company who provided the offer to improve your discoverability. 

If you did not use any additional offers and you are happy with the topics you have, feel free to close this issue.  👍

**Comment by rawheel** [comment]
I think for now the topics are fine.
