### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by ericdrosado** [rawheel/MyUnfollowers-App#7]
A README is often the first item a visitor will see when visiting your repository. From what I see with your current README, it looks good. I would recommend adding:

* A more thorough step by step for a user to clone and run this repo on their computer. 
* A section explaining that folks can learn how to recreate your project in the LEARN.md file. 
* A mention of your code of conduct.
* How to [contribute to your project](https://docs.github.com/en/get-started/quickstart/contributing-to-projects)

Depending on the complexity of your project, you might be interested in creating a [CONTRIBUTING.md](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) file, but we recommend starting simple with the bullet points above, and once you start to see an increase in users interested in contributing, you should consider a `CONTRIBUTING.md` file so you don’t find yourself overwhelmed with questions from other users.

**Comment by rawheel** [comment]
Added https://github.com/rawheel/MyUnfollowers-App/blob/main/README.md
