### ISSUE TITLE
Update repo description

### ISSUE THREAD

**Issue by ericdrosado** [rawheel/MyUnfollowers-App#8]
Other than GitHub Topics, your description will be the primary way of catching the users eyes. Your repo description should be clear and concise. Ask yourself:

* In one sentence, how do I convey what my repo does?
* What type of users am I interested in attracting to my repo?
* If I was a user, what words or phrases might spark my interest?

> Let's raid who unfollows you on GitHub. The app is developed using Python(Flask) Backend & Vuejs front end. 👻

I would recommend updating your description to be concise and clear about what your project does and why it is useful. Also, personal opinion, I am not a fan of the word "raid." The sentence, "Let's raid who unfollows you on GitHub" sounds aggressive, and is not very welcoming.

**Comment by rawheel** [comment]
I updated it to 

**🚀 A platform to inspect GitHub's followers/unfollowers with visualizations and stats.**

lmk if it fits or I'm how we can improve..

**Comment by ericdrosado** [comment]
This is perfect! Closing this issue. 🚀
